name: short_lived
description: Nostr short video app
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  video_player: ^2.8.1
  chewie: ^1.7.0
  dio: ^5.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  nostr: ^2.0.0
  shared_preferences: ^2.2.2
  collection: ^1.17.1
  equatable: ^2.0.5
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
