name: nostr_video
description: One-screen overlay UI Nostr short-video app.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: any
  video_player: ^2.9.1
  # Use hls.js behind the scenes on web; this registers itself instead of default web impl
  video_player_web_hls: ^1.2.0
  chewie: any
  dio: ^5.4.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: any
  collection: any
  equatable: any
  web_socket_channel: ^2.4.5
  url_launcher: ^6.3.0
  uuid: any
  flutter_secure_storage: ^9.0.0
  elliptic: ^0.3.11
  ecdsa: ^0.1.2
  crypto: ^3.0.0
  bech32: ^0.2.2
  qr_flutter: ^4.1.0
  share_plus: ^10.0.0
  http: ^1.2.2
  vector_graphics: ^1.1.7
  web: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: any
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: any
  network_image_mock: any
  stream_channel: ^2.1.2
  vector_graphics_compiler: ^1.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
