name: nostr_video
description: One-screen overlay UI Nostr short-video app.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: any
  video_player: any
  chewie: any
  dio: ^5.4.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  hive: any
  hive_flutter: any
  shared_preferences: any
  collection: any
  equatable: any
  web_socket_channel: ^2.4.0
  url_launcher: ^6.3.0
  uuid: any
  flutter_secure_storage: ^9.0.0
  elliptic: ^0.3.11
  ecdsa: ^0.1.2
  crypto: ^3.0.0
  bech32: ^0.2.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: any
  build_runner: any
  flutter_lints: any
  video_player_platform_interface: any
  network_image_mock: any
  stream_channel: ^2.1.2

flutter:
  uses-material-design: true
