name: nostr_video
description: One-screen overlay UI Nostr short-video app.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: any
  video_player: any
  chewie: any
  dio: any
  file_picker: ^8.0.0
  hive: any
  hive_flutter: any
  shared_preferences: any
  collection: any
  equatable: any
  web_socket_channel: ^2.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: any
  build_runner: any
  flutter_lints: any

flutter:
  uses-material-design: true
