name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Flutter Analyze
        run: flutter analyze
      - name: Guard against Placeholder widgets
        run: bash scripts/dev/find_placeholders.sh
      - name: Flutter Test
        run: flutter test
      - name: Build web artefacts
        run: flutter build web --release --pwa-strategy=offline-first
